//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoTest.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagOfClient
    {
        public int ClientID { get; set; }
        public int TagID { get; set; }
        public int TagClientID { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual Client Client { get; set; }
    }
}
